<h1 style="font-family: Arial; color: #bb0000">Applied Linear Algebra in Data Analysis</h1>

<h2 style="font-family: Arial; color: #666666">Application: Signal Processing</h2>



<b>Sivakumar Balasubramanian</b><br>
Department of Bioengineeering,<br>
Christian Medical College Vellore<br>
Tamil Nadu



<h2 style="color: #bb0000">Signals a Vectors</h2>

**What is a signal?** A signal is a function of an independent variable that conveys some information.

<img src="figs/breathing_t.svg" style="display: block; margin-left: auto; margin-right: auto; width:100%;">

<img src="figs/breathing_t.svg" style="display: block; margin-left: auto; margin-right: auto; width:70%;">

$x[n]$ in the above figure is a finite length signal of length $N$, where $n \in \mb{Z}, 0 \leq n < N$.

We can think of signal as a vector $\mf{x}$ in $\mb{R}^N$, i.e. this entire signal will be a point in $N$-dimensional space. Here, $N= 180$.

$$ \mf{x} = \bmx x[0] & x[1] & x[2] & \cdots & x[N-1]\emx^\top $$

<img src="figs/breathing_t.svg" style="display: block; margin-left: auto; margin-right: auto; width:70%;">

The above representation of $x[n]$ is in the standard basis $\lc \mf{e}_1, \mf{e}_2, \ldots \mf{e}_N\rc$.

$$ \mf{x} = x[0] \cdot \mf{e}_1 + x[1] \cdot \mf{e}_2 + \cdots + x[N-1] \cdot \mf{e}_N $$


What would this signal look like in a different basis?

<h2 style="color: #bb0000">Discrete Fourier Transform: the Fourier Basis</h2>

For rhythmic signals, the Fourier basis is often useful. We will need to switch to the complex vector space $\mb{C}^N$ to work with the Fourier basis.
    
Consider the following complex exponential signals of length $N$,
$$
  \begin{split}
    w_k[n] &= e^{j \frac{2\pi k}{N}n}, \,\, 0 \leq n, k < N \\
           &= \cos\lp \frac{2\pi k}{N}n\rp + j \sin \lp \frac{2\pi k}{N}n\rp
  \end{split}
$$

We can represent this as a vector $\mf{w}_k \in \mb{C}^N$, where
$$ \mf{w}_k = \bmx w_k[0] & w_k[1] & w_k[2] & \cdots & w_k[N-1] \emx^\top, \,\,\ 0 \leq k < N-1 $$
    
There are $N$ such $\mf{w}_k$ vectors in $\mb{C}^N$.

The $\mf{w}_k$ vectors satisfy the following property,
$$ \mf{w}_i^*\mf{w}_k = \begin{cases} N &, i = k \\ 0 &, i \neq k \end{cases} $$

We define na orthonomgal basis for $\mb{C}^N$ as $\mc{F} = \lc \frac{1}{\sqrt{N}} \mf{w}_k \rc_{k=0}^{N-1}$.
    
Using this orthonormal basis, we define the **Fourier matrix** as the following,
$$ \mf{F}_N = \frac{1}{\sqrt{N}} \bmx \mf{w}_0 & \mf{w}_1 & \cdots & \mf{w}_{N-1} \emx $$

It can be verified that $\mf{F}_N$ is a unitary matrix, i.e. $\mf{F}_N^H \mf{F}_N = \mf{I}_N$.

The representation of a signal $\mf{x}$ in the Fourier basis is given by,
$$ \mf{x}_{\mc{F}} = \mf{F}_{N}^{-1} \mf{x} = \mf{F}_N^H \mf{x} $$

$\mf{x}_{\mc{F}}$ representation is called the **Discrete Fourier Transform** (DFT) of $\mf{x}$.

The inverse DFT, i.e. obtaining the $\mf{x}$ from $\mf{X}_{\mc{F}}$, is given by,
$$ \mf{x} = \mf{F}_N \mf{x}_{\mc{F}} $$

$\mf{x}$ is the called the *time domain* representation of the signal, while $\mf{x}_{\mc{F}}$ is the *frequency domain* representation of the signal.

Let's dig a little deeper to understand the Fourier basis.

In [6]:
N = 5
FN = fourier_basis(N)

# Sinusoidal time-domain signal
n = np.arange(N)
amp, freq, phase = 1.0, 1.0, 0

# Time domain signal
x1 = amp * np.cos(2 * np.pi * freq * n / N + phase * np.pi / 180).reshape((-1, 1))

# Representation in the Fourier basis
Xf1 = FN.conj().T @ x1

# Print the representation.
print_signals(x1, Xf1)

Standard basis representation: 
[ 1.     0.309 -0.809 -0.809  0.309]
Forurier basis representation: 
[-0.   +0.j  1.118-0.j  0.   -0.j  0.   -0.j  1.118+0.j]
Magnitude:      0.00,    1.12,    0.00,    0.00,    1.12
Angle.   :      0.00,   -0.00,   -0.00,   -0.00,    0.00


<h2 style="color: #bb0000">Sinusoids have sparse representation in the Fourier basis</h2>

$$ x_1[n] = A \sin \lp 2\pi \frac{50}{N} n\rp$$

<img src="figs/signal1_fft.svg" style="display: block; margin-left: auto; margin-right: auto; width:80%;">

<h2 style="color: #bb0000">Sinusoids have sparse representation in the Fourier basis</h2>

$$ x_2[n] = A_1 \sin \lp 2\pi \frac{5}{N} n\rp + A_2 \sin \lp 2\pi \frac{25}{N} n\rp + A_3 \sin \lp 2\pi \frac{50}{N} n\rp + A_4 \sin \lp 2\pi \frac{350}{N} n\rp$$

<img src="figs/signal2_fft.svg" style="display: block; margin-left: auto; margin-right: auto; width:80%;">

<h2 style="color: #bb0000">Sinusoids have sparse representation in the Fourier basis</h2>

What happens when the frequency index $k$ is not an integer.
$$ x_2[n] = A_1 \sin \lp 2\pi \frac{76.1}{N} n\rp $$

<img src="figs/signal3_fft.svg" style="display: block; margin-left: auto; margin-right: auto; width:80%;">

<h2 style="color: #bb0000">Frequency domain representation of $x[n]$</h2>

<img src="figs/breathing_t.svg" style="display: block; margin-left: auto; margin-right: auto; width:100%;">

<img src="figs/breathing_fft.svg" style="display: block; margin-left: auto; margin-right: auto; width:100%;">

<h2 style="color: #bb0000">Problems with the Fourier Basis</h2>

<img src="figs/signal_transient.svg" style="display: block; margin-left: auto; margin-right: auto; width:80%;">

<h2 style="color: #bb0000">Wavelet Basis</h2>

Wavelet basis are localized in time and frequency, making them suitable for transient signals.
  
The **Haar wavelet** is the simplest wavelet basis. Consider a the vector space $\mb{R}^8$, the Haar wavelet basis $\mc{W} = \lc \mf{h}_k \rc_{k=1}^8$ for this space is given by,

$$\scriptscriptstyle \mf{h}_1 = \frac{1}{\sqrt{8}}\bmx 1 \\ 1 \\ 1 \\ 1 \\ 1 \\ 1 \\ 1 \\ 1 \emx \,\, 
  \mf{h}_2 = \frac{1}{\sqrt{8}}\bmx 1 \\ 1 \\ 1 \\ 1 \\ -1 \\ -1 \\ -1 \\ -1 \emx \,\, 
  \mf{h}_3 = \frac{1}{2}\bmx 1 \\ 1 \\ -1 \\ -1 \\ 0 \\ 0 \\ 0 \\ 0 \emx \,\, 
  \mf{h}_4 = \frac{1}{2}\bmx 0 \\ 0 \\ 0 \\ 0 \\ 1 \\ 1 \\ -1 \\ -1 \emx \,\, 
  \mf{h}_5 = \frac{1}{\sqrt{2}}\bmx 1 \\ -1 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \emx \,\, 
  \mf{h}_6 = \frac{1}{\sqrt{2}}\bmx 0 \\ 0 \\ 1 \\ -1 \\ 0 \\ 0 \\ 0 \\ 0 \emx \,\, 
  \mf{h}_7 = \frac{1}{\sqrt{2}}\bmx 0 \\ 0 \\ 0 \\ 0 \\ 1 \\ -1 \\ 0 \\ 0 \emx \,\, 
  \mf{h}_8 = \frac{1}{\sqrt{2}}\bmx 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 1 \\ -1 \emx $$
  
$$ \mf{W}_8 = \bmx \mf{h}_1 & \mf{h}_2 & \mf{h}_3 & \mf{h}_4 & \mf{h}_5 & \mf{h}_6 & \mf{h}_7 & \mf{h}_8 \emx $$

The wavelet basis is a an orthonormal basis for $\mb{R}^8$.
$$  \mf{W}_8^H \mf{W}_8 = \mf{I} $$

Let $x[n], \,\, 0 \leq n < 8$ be a signal of length $8$, which can represented in the standard basis of $\mb{R}^8$ as,
$$ \mf{x} = \bmx x[0] & x[1] & x[2] & \cdots & x[7] \emx^\top $$

The resentation of this signal is the wavelet basis is given by,
$$ \mf{x}_{\mc{W}} = \mf{W}_8^{-1} \mf{x} = \mf{W}_8^{\top} \mf{x} $$

The Haar wavelet provides a sparse representation of the red and blue signals, because they are well matched with the Haar bases.

<img src="figs/signal_transient_wavedec.svg" style="display: block; margin-left: auto; margin-right: auto; width:80%;">


When the signal is not well matched with the wavelet basis, the representation is not sparse or less sparse.

<img src="figs/sine_transient_wavedec.svg" style="display: block; margin-left: auto; margin-right: auto; width:80%;">


Definiting custom latex commands:

$$
\newcommand{\mb}{\mathbb}
\newcommand{\mf}{\mathbf}
\newcommand{\mc}{\mathcal}
\newcommand{\bmx}{\begin{bmatrix}}
\newcommand{\emx}{\end{bmatrix}}
\newcommand{\lc}{\left\{}
\newcommand{\rc}{\right\}}
\newcommand{\lp}{\left(}
\newcommand{\rp}{\right)}
$$

In [50]:
import numpy as np
import sys
np.set_printoptions(precision=3, suppress=True)

def fourier_basis(N: int) -> np.array:
    """Returns the Fourier basis in C^N.
    """
    return np.array([
        [np.exp((2 * np.pi * k * n * 1j) / N) for k in range(N)]
        for n in range(N)
    ]) / np.sqrt(N)


def get_angle(x: np.array) -> np.array:
    """Retuns angle for the given complex number.
    When the absolute value is 0, it returns 0 as the
    angle."""
    _nonzero = np.sign(np.around(np.abs(x)))
    return _nonzero * np.array(
        np.rad2deg(np.angle(x))
    )

def print_signals(xt: np.array, Xf: np.array):
    """Print the time data.
    """
    print("Standard basis representation: ")
    print(xt.T[0])
    print("Forurier basis representation: ")
    print(Xf.T[0])
    print("Magnitude: ", ','.join([f"{_r:-8.2f}" for _r in np.abs(Xf.T[0])]))
    print("Angle.   : ", ','.join([f"{_r:-8.2f}" for _r in get_angle(Xf.T[0])]))
    
def haar_basis(N: int) -> np.array:
    """Returns the Haar basis in R^N.
    """
    if N % 2 != 0:
        raise ValueError("N must be a power of 2")
    
    H = np.zeros((N, N))
    H[:, 0] = 1 / np.sqrt(N)

    # Compute the Haar wavelet basis
    step = 1

    for i in range(1, N):
        j = int(np.floor(np.log2(i)))
        shift = N // (2 ** j)
        k = (i % 2 ** j) * shift
        H[k:k+shift//2, i] = 1 / np.sqrt(shift)
        H[k+shift//2:k+shift, i] = - 1 / np.sqrt(shift)
    return H

In [49]:
def haar_basis(N: int) -> np.array:
    """Returns the Haar basis in R^N.
    """
    if N % 2 != 0:
        raise ValueError("N must be a power of 2")
    
    H = np.zeros((N, N))
    H[:, 0] = 1 / np.sqrt(N)

    # Compute the Haar wavelet basis
    step = 1

    for i in range(1, N):
        j = int(np.floor(np.log2(i)))
        shift = N // (2 ** j)
        print(i, j, shift, i % 2 ** j)
        k = (i % 2 ** j) * shift
        H[k:k+shift//2, i] = 1 / np.sqrt(shift)
        H[k+shift//2:k+shift, i] = - 1 / np.sqrt(shift)
    return H

In [3]:
N = 4
W4 = fourier_basis(N)
n = np.arange(N)

# Sinusoidal signal
f = 1.23
x1 = np.cos(2 * np.pi * f * n / N + 0.12 * np.pi).reshape((-1, 1))

Xf1 = W4.conj().T @ x1

print(x1.T[0])
print(Xf1.T[0])
print(np.abs(Xf1.T[0]))
print(get_angle(Xf1.T[0]))

[ 0.93  -0.673 -0.454  0.994]
[0.398+0.j    0.692+0.833j 0.077-0.j    0.692-0.833j]
[0.398 1.083 0.077 1.083]
[  0.     50.304  -0.    -50.304]


In [28]:
print(np.sign(np.around(np.abs(Xf1.T[0]), 3)))

[0. 1. 0. 1.]
